name: 'Branch Action'
description: 'Simplify the work with git branches'

inputs:
  branch:
    description: 'A git branch name'
    required: true
  action:
    description: 'An action to execute'
    required: true

outputs:
  exists:
    description: 'Branch existence'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'play'
  color: 'gray-dark'